// Harvest donor bundles from a PST export fixture (CLAUDE.md §6 donor pattern).
//
// For each object type in the fixture, capture a pristine copy of one
// instance: its map_object entry plus the works and item_containers it owns.
// Placing a "new" object in the editor clones one of these bundles with fresh
// GUIDs — nothing is ever constructed from first principles (C4).
//
// Usage: npx tsx tools/harvest-donors.ts [fixture.json] [out.json]
import { readFileSync, writeFileSync } from "node:fs";

const inPath = process.argv[2] ?? "fixtures/calibration_01.json";
const outPath = process.argv[3] ?? "src/data/donors.json";

/* eslint-disable @typescript-eslint/no-explicit-any */
const raw: any = JSON.parse(readFileSync(inPath, "utf8"));
if (!Array.isArray(raw?.map_objects)) throw new Error(`${inPath}: no map_objects array`);

const donors: Record<string, unknown> = {};
for (const mo of raw.map_objects) {
  const typeId = mo?.MapObjectId?.value;
  if (typeof typeId !== "string" || donors[typeId]) continue;

  const rd = mo?.Model?.value?.RawData?.value;
  const id = rd?.instance_id;
  if (typeof id !== "string") {
    console.warn(`skipping a ${typeId}: no Model instance_id`);
    continue;
  }
  const works = (raw.works ?? []).filter(
    (w: any) => w?.RawData?.value?.owner_map_object_model_id === id
  );
  const containerIds = new Set(
    (mo?.ConcreteModel?.value?.ModuleMap?.value ?? [])
      .map((m: any) => m?.value?.RawData?.value?.target_container_id)
      .filter((c: unknown) => typeof c === "string")
  );
  const item_containers = (raw.item_containers ?? []).filter((c: any) =>
    containerIds.has(c?.key?.ID?.value)
  );
  donors[typeId] = { map_object: mo, works, item_containers };
  console.log(
    `harvested ${typeId}: ${works.length} work(s), ${item_containers.length} container(s)`
  );
}

const out = {
  _meta: {
    note: "Generated by tools/harvest-donors.ts — do not hand-edit. Every bundle is a verbatim copy from a real PST export (CLAUDE.md C4/§6).",
    sourceFixture: inPath.replace(/\\/g, "/"),
    harvestedAt: new Date().toISOString(),
  },
  donors,
};
writeFileSync(outPath, JSON.stringify(out, null, 1));
console.log(`\nwrote ${Object.keys(donors).length} donor types to ${outPath}`);
