// Harvest donor bundles from a PST export fixture (CLAUDE.md §6 donor pattern).
//
// For each object type in the fixture, capture a pristine copy of one
// instance: its map_object entry plus the works and item_containers it owns.
// Placing a "new" object in the editor clones one of these bundles with fresh
// GUIDs — nothing is ever constructed from first principles (C4).
//
// Usage: npx tsx tools/harvest-donors.ts [fixture.json ...]
//   Reads every fixture given (default: all fixtures/*.json), merges into
//   src/data/donors.json. First occurrence of a type wins, in argument order —
//   re-running with a new export only ADDS types, existing donors are kept.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";

/* eslint-disable @typescript-eslint/no-explicit-any */
const args = process.argv.slice(2);
const inPaths = args.length
  ? args
  : readdirSync("fixtures")
      .filter((f) => f.endsWith(".json"))
      .map((f) => `fixtures/${f}`);
const outPath = "src/data/donors.json";

const donors: Record<string, unknown> = {};
const sources: Record<string, string> = {};

for (const inPath of inPaths) {
  const raw: any = JSON.parse(readFileSync(inPath, "utf8"));
  if (!Array.isArray(raw?.map_objects)) {
    console.warn(`${inPath}: no map_objects array — skipped`);
    continue;
  }
  for (const mo of raw.map_objects) {
    const typeId = mo?.MapObjectId?.value;
    if (typeof typeId !== "string" || donors[typeId]) continue;

    const rd = mo?.Model?.value?.RawData?.value;
    const id = rd?.instance_id;
    if (typeof id !== "string") {
      console.warn(`skipping a ${typeId} in ${inPath}: no Model instance_id`);
      continue;
    }
    const works = (raw.works ?? []).filter(
      (w: any) => w?.RawData?.value?.owner_map_object_model_id === id
    );
    const containerIds = new Set(
      (mo?.ConcreteModel?.value?.ModuleMap?.value ?? [])
        .map((m: any) => m?.value?.RawData?.value?.target_container_id)
        .filter((c: unknown) => typeof c === "string")
    );
    const item_containers = (raw.item_containers ?? []).filter((c: any) =>
      containerIds.has(c?.key?.ID?.value)
    );
    donors[typeId] = { map_object: mo, works, item_containers };
    sources[typeId] = inPath.replace(/\\/g, "/");
    console.log(
      `harvested ${typeId} from ${inPath}: ${works.length} work(s), ${item_containers.length} container(s)`
    );
  }
}

const out = {
  _meta: {
    note: "Generated by tools/harvest-donors.ts — do not hand-edit. Every bundle is a verbatim copy from a real PST export (CLAUDE.md C4/§6).",
    sources,
    harvestedAt: new Date().toISOString(),
  },
  donors,
};
writeFileSync(outPath, JSON.stringify(out, null, 1));
console.log(`\nwrote ${Object.keys(donors).length} donor types to ${outPath}`);
